version: '3.1'
name: "src"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
  mq:
    image: apache/activemq-artemis:latest-alpine
    restart: always
    environment:
      ARTEMIS_USER: ea
      ARTEMIS_PASSWORD: cs544
      ANONYMOUS_LOGIN: true
      EXTRA_ARGS: "--name cs544broker --no-autotune"