version: '3.1'
services:
  backend-main:
    container_name: backend-main
    build:
      context: ./../
      dockerfile: docker/backend.Dockerfile
    volumes:
      - ./../EAProjectMain/src:/app/src
      - ./../EAProjectMain/target:/app/target
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - my-network
  backend-second:
    container_name: backend-second
    build:
      context: ./../
      dockerfile: docker/backend-second.Dockerfile
    volumes:
      - ./../EAProjectSecond/src:/app/src
      - ./../EAProjectSecond/target:/app/target
    ports:
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - my-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
    networks:
      - my-network
  mq:
    image: apache/activemq-artemis:latest-alpine
    restart: always
    environment:
      ARTEMIS_USER: ea
      ARTEMIS_PASSWORD: cs544
      ANONYMOUS_LOGIN: true
      EXTRA_ARGS: "--name cs544broker --no-autotune"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
