version: '3.1'
services:
  my-backend:
    container_name: my-backend
    build:
      context: ./../
      dockerfile: docker/backend.Dockerfile
    volumes:
      - ./../src:/app/src
      - ./../target:/app/target
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      - SPRING_PROFILES_ACTIVE=dev
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - my-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
  mq:
    image: apache/activemq-artemis:latest-alpine
    restart: always
    environment:
      ARTEMIS_USER: ea
      ARTEMIS_PASSWORD: cs544
      ANONYMOUS_LOGIN: true
      EXTRA_ARGS: "--name cs544broker --no-autotune"
networks:
  my-network:
    driver: bridge
