version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: eaproject
  mq:
    image: apache/activemq-artemis:latest-alpine
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ARTEMIS_USER: ea
      ARTEMIS_PASSWORD: cs544
      ANONYMOUS_LOGIN: "true"